default: &default
  adapter: mysql
  pool: 5
  timeout: 5000

production:
  <<: *default
  database: umasstransit_st_rodeo_production

development:
  <<: *default
  database: umasstransit_rodeo_development

test:
  <<: *default
  database: umasstransit_rodeo_test
